package dk.siema.siemaexamproject.dal.dao;

import dk.siema.siemaexamproject.be.Box;
import dk.siema.siemaexamproject.be.Document;
import dk.siema.siemaexamproject.be.FileEntity;
import dk.siema.siemaexamproject.dal.exception.DalException;
import dk.siema.siemaexamproject.dal.ConnectionManager;
import dk.siema.siemaexamproject.dal.interfaces.IBoxDAO;
import dk.siema.siemaexamproject.dal.util.BytesConverter;

import java.sql.*;

public class BoxDAO implements IBoxDAO {

    public void saveBox(Box box) throws DalException {
        String insertBox = "INSERT INTO Boxes (profile_id) VALUES (?)";
        String insertDoc = "INSERT INTO Documents (box_id) VALUES (?)";
        String insertFile = "INSERT INTO FileEntities (document_id, reference_id, sort_order, rotation, is_barcode, file_data) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = ConnectionManager.getConnection()) {

            try {
                conn.setAutoCommit(false); // START TRANSACTION

                try (PreparedStatement boxStmt = conn.prepareStatement(insertBox, Statement.RETURN_GENERATED_KEYS);
                     PreparedStatement docStmt = conn.prepareStatement(insertDoc, Statement.RETURN_GENERATED_KEYS);
                     PreparedStatement fileStmt = conn.prepareStatement(insertFile)) {

                    // 1. Save Box
                    boxStmt.setString(1, box.getProfileId());
                    boxStmt.executeUpdate();
                    box.setId(getGeneratedId(boxStmt));

                    // 2. Save Documents
                    for (Document doc : box.getDocuments()) {
                        docStmt.setInt(1, box.getId());
                        docStmt.executeUpdate();
                        doc.setId(getGeneratedId(docStmt));

                        // 3. Save Files
                        for (FileEntity file : doc.getFiles()) {
                            fileStmt.setInt(1, doc.getId());
                            fileStmt.setBytes(2, BytesConverter.uuidToBytes(file.getReferenceId()));
                            fileStmt.setInt(3, file.getSortOrder());
                            fileStmt.setInt(4, file.getRotation());
                            fileStmt.setBoolean(5, file.isBarcode());
                            fileStmt.setBytes(6, file.getFileData());
                            fileStmt.addBatch(); // add to the bucket instead of sending immediately
                        }
                        fileStmt.executeBatch(); //send the whole bucket at once
                        conn.commit(); // COMMIT TRANSACTION
                    }


                }
            } catch (SQLException e) {
                conn.rollback(); // Undo everything if it fails
                throw new DalException("Database transaction failed while saving the Box hierarchy.", e);
            } finally {
                conn.setAutoCommit(true);
            }
        } catch (SQLException e) {
            // Catch connection issues
            throw new DalException("Could not connect to the database to save the export.", e);
        }
    }

    private int getGeneratedId(PreparedStatement stmt) throws DalException {
        try (ResultSet rs = stmt.getGeneratedKeys()) {
            if (rs.next()) return rs.getInt(1);
        } catch (SQLException e) {
            throw new DalException("Failed to retrieve generated ID from database.", e);
        }
        throw new DalException("No ID was generated by the database.");
    }
}

