package dk.siema.siemaexamproject.dal.dao;

import dk.siema.siemaexamproject.be.Box;
import dk.siema.siemaexamproject.be.Document;
import dk.siema.siemaexamproject.be.FileEntity;
import dk.siema.siemaexamproject.dal.exception.DalException;
import dk.siema.siemaexamproject.dal.ConnectionManager;
import dk.siema.siemaexamproject.dal.interfaces.IBoxDAO;
import dk.siema.siemaexamproject.dal.util.BytesConverter;

import java.sql.*;

public class BoxDAO implements IBoxDAO {

    public void saveBoxHierarchy(Box box) throws DalException {
        String insertBox = "INSERT INTO Boxes (ProfileId) VALUES (?)";
        String insertDoc = "INSERT INTO Documents (BoxId, Status) VALUES (?, ?)";
        String insertFile = "INSERT INTO Files (DocumentId, ReferenceId, SortOrder, FilePath, Rotation, IsBarcode) VALUES (?, ?, ?, ?, ?, ?)";

        try (Connection conn = ConnectionManager.getConnection()) {

            try {
                conn.setAutoCommit(false); // START TRANSACTION

                try (PreparedStatement boxStmt = conn.prepareStatement(insertBox, Statement.RETURN_GENERATED_KEYS);
                     PreparedStatement docStmt = conn.prepareStatement(insertDoc, Statement.RETURN_GENERATED_KEYS);
                     PreparedStatement fileStmt = conn.prepareStatement(insertFile)) {

                    // 1. Save Box
                    boxStmt.setString(1, box.getProfileId());
                    boxStmt.executeUpdate();
                    box.setId(getGeneratedId(boxStmt));

                    // 2. Save Documents
                    for (Document doc : box.getDocuments()) {
                        docStmt.setInt(1, box.getId());
                        docStmt.setString(2, doc.getStatus());
                        docStmt.executeUpdate();
                        doc.setId(getGeneratedId(docStmt));

                        // 3. Save Files
                        for (FileEntity file : doc.getPages()) {
                            fileStmt.setInt(1, doc.getId());
                            fileStmt.setBytes(2, BytesConverter.uuidToBytes(file.getReferenceId()));
                            fileStmt.setInt(3, file.getSortOrder());
                            fileStmt.setString(4, file.getFilePath());
                            fileStmt.setInt(5, file.getRotation());
                            fileStmt.setBoolean(6, file.isBarcode());
                            fileStmt.executeUpdate();
                        }
                    }
                    conn.commit(); // COMMIT TRANSACTION

                }
            } catch (SQLException e) {
                conn.rollback(); // Undo everything if it fails
                throw new DalException("Database transaction failed while saving the Box hierarchy.", e);
            } finally {
                conn.setAutoCommit(true);
            }
        } catch (SQLException e) {
            // Catch connection issues
            throw new DalException("Could not connect to the database to save the export.", e);
        }
    }

    private int getGeneratedId(PreparedStatement stmt) throws DalException {
        try (ResultSet rs = stmt.getGeneratedKeys()) {
            if (rs.next()) return rs.getInt(1);
        } catch (SQLException e) {
            throw new DalException("Failed to retrieve generated ID from database.", e);
        }
        throw new DalException("No ID was generated by the database.");
    }
}

